### ISSUE TITLE
Missing class

### ISSUE THREAD

**Issue by gsouf** [zephir-lang/idea-plugin#2]
I think a class is missing in the repository, or maybe am I missing something :

When I build the plugin I got an error about this line https://github.com/zephir-lang/idea-plugin/blob/master/src/com/zephir/lang/ZephirBraceMatcher.java#L7 

It tells that the class com.zephir.psi.ZephirTypes does not exist. I checked, it does not exist in the repo neither

**Comment by nkt** [comment]
I'm not sure, but guess, this code is generated by jflex.
Try `right-click` on https://github.com/zephir-lang/idea-plugin/blob/master/src/com/zephir/Zephir.bnf file and run something like `generate AST classes`

**Comment by gsouf** [comment]
Got it ! I was missing the "grammar kit" plugin. 

Should we ship add the generated class to the repository ?

**Comment by nkt** [comment]
Nope. These files could be generated, so they are ignored.

**Comment by gsouf** [comment]
Ok, do you know if is there a way to add their generation to the build process ? If you dont know I can search for it.

**Comment by nkt** [comment]
Nope, I don't know.

**Comment by gsouf** [comment]
Ok, thanks btw !
